eetStrings = {

	EET_CMP_TEXT_BG1 = "\"He who fights with monsters should look to it that he himself does not become a monster... when you gaze long into the abyss the abyss also gazes into you...\" -Friedrich Nietzsche.\n\nFor as long as you can remember, your view of the world has been limited to the heavily fortified walls of Candlekeep. Your foster father, Gorion, has done everything in his power to protect you and keep you out of harm's way.\n\nAll of that is about to change. Forced to leave your home under mysterious circumstances, you find yourself drawn into a conflict that has the Sword Coast on the brink of war. An iron shortage of unknown origin threatens to plunge the city of Baldur's Gate into conflict with Amn. Meanwhile, there is something else at work, far more sinister than you can even begin to fathom...",
	EET_CMP_TEXT_SOD = "\"Fate leads him who follows it, and drags him who resist.\" -Plutarch\n\nThe threat of war looms over the city of Baldur's Gate. A crusade marches from the north, seizing supplies, forcing locals into military service, and disrupting trade along the Sword Coast. A charismatic warrior known as the Shining Lady leads this army, her background shrouded in mystery. Rumors whisper that she follows a divine agenda. Could the gods truly guide this Shining Lady?\n\nThe farther you travel from the city, the more you realize how many forces have a stake in the outcome of this conflict. Baldur's Gate has put its faith in you, but you must determine whose interests you truly serve before you face the Shining Lady among the ruins of Dragonspear Castle...",
	EET_CMP_TEXT_SOA = "\"The Lord of Murder shall perish, but in his doom he shall spawn a score of mortal progeny. Chaos shall be sown from their passage...\" -So sayeth the Wise Alaundo\n\nKidnapped. Imprisoned. Tortured. The wizard Irenicus holds you captive in his stronghold, attempting to strip you of the powers that are your birthright.\n\nCan you resist the evil within you, forge a legend of heroic proportions, and ultimately destroy the dark essence that haunts your dreams? Or will you embrace your monstrous nature, carve a swath of destruction across the realms, and ascend to godhood as the new Lord of Murder?",
	EET_CMP_TEXT_TOB = "\"There is no peace for a child of Bhaal. You've learned this lesson time and again. As all who are close to you suffer; because, of your tainted blood.\"\n\nWelcome to Baldur's Gate II: Throne of Bhaal, the expansion pack to Baldur's Gate II: Shadows of Amn, and the final chapter in the Baldur's Gate series. The time of the prophecy has come.",
	EET_CMP_TEXT_BP1 = "\"Come one, come all! Feast your eyes upon most marvelous martial magnificence that the Underdark has to offer!\" -Baeloth the Entertainer\n\nDeep within the Underdark where few dare to tread, the mad drow Baeloth has used his extensive mastery of magic to force a duergar colony into creating an entertainment complex of his own design. He has invited guests from across the realms, from Maztica to Menzoberranzan, and they will readily attend - Baeloth is known to be an excellent showman.",
	EET_CMP_TEXT_BP2 = "\"Come one, come all! To the greatest show this side of the Astral plane!\" -Dennaton\n\nWelcome to Black Pits II: Gladiators of Thay, a follow-up to Baeloth's Black Pits. Explore the tactical depth of high-level Dungeons & Dragons combat. Turn your captors against each other while you dodge traps and battle for your life against Demi-Liches, Mind Flayers, and the legendary Githyanki.",
	EET_CMP_TEXT_TUT = "\"Hello, child. Shall we continue your lessons?\" -Tutor\n\nWelcome to the Ducal Palace, the tutorial area for Baldur's Gate: Enhanced Edition. This is a simple walk-through of some of the basic skills you will need to play and enjoy the game. Once the tutorial area has loaded, an NPC (non-player character) will guide you through fighting monsters, casting spells, the use of thieving abilities, and some of the more common interactions you will experience in the game world.",
	EET_CMP_TITLE_BG1 = "Baldur's Gate",
	EET_CMP_TITLE_SOD = "Siege of Dragonspear",
	EET_CMP_TITLE_SOA = "Shadows of Amn",
	EET_CMP_TITLE_TOB = "Throne of Bhaal",
	EET_CMP_TITLE_BP1 = "The Black Pits",
	EET_CMP_TITLE_BP2 = "Gladiators of Thay",
	EET_CMP_TITLE_TUT = "Tutorial",
	EET_WARNING_TITLE = "WARNING",
	EET_WARNING_TEXT = "Baldur's Gate: Enhanced Edition Trilogy mod installation has not been finished yet.\n\nAFTER installing all other mods please run \"setup-EET_end.exe\" to finalise the installation.\n\nIf you're unsure what to do please check the readme file included in the mod package.",
	EET_CHAPTER = "Chapter ",
}

cheatAreasExpansion = {
	{"BD0010", "Ducal Palace City Exterior"},
	{"BD0020", "Sorcerous/Elf Song City Exterior"},
	{"BD0030", "Flaming Fist City Exterior"},
	{"BD0040", "Three Kegs City Exterior"},
	{"BD0050", "Iron Throne City Exterior"},
	{"BD0060", "Random Area - Cave Entrance"},
	{"BD0061", "Random Area - Cave Interior from BD0060"},
	{"BD0062", "Random Area - Cave Pool from BD0061"},
	{"BD0063", "Random Area - Canyon Ambush"},
	{"BD0064", "Random Area - Forest Paths"},
	{"BD0065", "Random Area - Wilderness Open Area"},
	{"BD0066", "Random Area - Wilderness Hole to BD0067"},
	{"BD0067", "Random Area - Cave Interior from BD0066"},
	{"BD0070", "The Scrying Pool - The Hooded Man Cutscene"},
	{"BD0071", "The Scrying Pool - Caelar Cutscene"},
	{"BD0100", "Ducal Palace, Second Floor"},
	{"BD0101", "Ducal Palace, Leaving BG"},
	{"BD0102", "Ducal Palace, First Floor"},
	{"BD0103", "Ducal Palace, Third Floor"},
	{"BD0104", "Flaming Fist HQ"},
	{"BD0105", "Flaming Fist HQ, Basement"},
	{"BD0106", "Three Old Kegs, First Floor"},
	{"BD0107", "Three Old Kegs, Second Floor"},
	{"BD0108", "Three Old Kegs, Third Floor"},
	{"BD0109", "Elfsong Tavern, First Floor"},
	{"BD0110", "Elfsong Tavern, Second Floor"},
	{"BD0111", "Iron Throne Floor, First Floor"},
	{"BD0112", "Baldur's Gate East"},
	{"BD0113", "Underground Cavern Wyrms"},
	{"BD0114", "Spider Cave"},
	{"BD0115", "Vampire Cavern"},
	{"BD0116", "Ducal Palace, Basement"},
	{"BD0117", "Iron Throne, Basement"},
	{"BD0118", "The Scrying Pool - Imoen Cutscene"},
	{"BD0120", "Tomb Safehouse, First Floor"},
	{"BD0121", "Sorcerous Sundries, First Floor"},
	{"BD0122", "Sorcerous Sundries, Second Floor"},
	{"BD0130", "Tomb Safehouse, Second Floor"},
	{"BD1000", "Coast Way Crossing"},
	{"BD1010", "Cave (generic)"},
	{"BD1100", "The Dig"},
	{"BD1200", "Lich Outpost"},
	{"BD2000", "Boareskyr Bridge & Bridgefort"},
	{"BD2010", "Cave (generic)"},
	{"BD2100", "Bridgefort Interior"},
	{"BD3000", "Allied Siege Camp"},
	{"BD4000", "Dragonspear Castle, Exterior"},
	{"BD4100", "Dragonspear Castle Keep, First Floor"},
	{"BD4300", "Dragonspear Castle Basement"},
	{"BD4400", "Avernus"},
	{"BD4500", "Avernus Bridge"},
	{"BD4600", "Avernus Interior"},
	{"BD4601", "Avernus Elevator"},
	{"BD4700", "Avernus Roof"},
	{"BD5000", "Underground River Entrance"},
	{"BD5100", "Underground River"},
	{"BD5110", "Ettin Ghost Cave"},
	{"BD5200", "The Warrens"},
	{"BD5300", "Kanaglym"},
	{"BD6000", "Abandoned Sewers & Caverns"},
	{"BD6200", "Sewers Exit"},
	{"BD6100", "The Ambush"},
	{"BD7000", "Coast Way Forest"},
	{"BD7100", "Troll Forest"},
	{"BD7110", "Troll Cave"},
	{"BD7200", "Forest of Wyrms"},
	{"BD7210", "Wyrm Cave"},
	{"BD7220", "Bugbear Stronghold"},
	{"BD7230", "Temple of Cyric"},
	{"BD7300", "Dead Man's Pass"},
	{"BD7310", "Hidden Cellar/Treasure Stash"},
	{"BD7400", "Bloodbark Grove"},
	{"BD7410", "Vampire Hideout"},
}